version: "3.9"
services:
  web-app:
    container_name: fs4r_webapp
    image: ghcr.io/vanderkast/fs4r-webapp/fs4rwebapp:latest
    ports:
      - "3000:80"
  backend:
    container_name: fs4r_service
    image: ghcr.io/vanderkast/fs4r/fs4rservice:latest
    ports:
      - "8080:8080"
